config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :products do
    resources :comments, only: [:create, :update, :destroy]
  end

  root to: "products#index"  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product

  validates :text, presence: true

  def created_at_h
    created_at.strftime('%B %d, %Y at %I:%M%p')
  end
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :comments, dependent: :destroy

  validates :title, :description, :amount, :price, presence: true

  def truncated_description
	truncate(self.description, length:64)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def administrator?
  	role == "administrator"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_product, only: [:create, :update]

  # def index
  #   @comments = Comment.all
  # end

  def new
    @comment = Comment.new
  end

  # def edit
  # end

  def create
    @comment = @product.comments.new(comment_params)
    @comment.save
  end

  # def update
  #   if @comment.update(comment_params)
  #     redirect_to @comment, notice: 'Comment was successfully updated.'
  #   else
  #     render :edit
  #   end
  # end

  def destroy
    @comment.destroy

    # redirect_to comments_url, notice: 'Comment was successfully destroyed.'
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_product
      @product = Product.find(params[:product_id])
    end

    def comment_params
      params.require(:comment).permit(:product_id, :text)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # expose :product
  # expose :comment, -> {product.comments.new}


  def index
    products = Product.all
    products = products.where("title ILIKE ?", "%#{params[:search]}%") if params[:search]
    
    @products = products.map {|product| ProductDecorator.new(product, current_user)}

  end

  def show
    @comment = Comment.new
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @policy.destroy?
      @product.destroy
    else
      redirect_to root_path, alert: "Sorry, you don't have perms" and return
    end

    redirect_to products_url, notice: 'Product was successfully destroyed.' and return
  end

  private
    def set_product
      @product = Product.find(params[:id])
      @policy = ProductPolicy.new(@product, current_user)
    end

    def authorize!
      action = params[:action] # destroy
      redirect_to root_path, alert: "Sorry, you don't have perms"
    end

    def product_params
      params.require(:product).permit(:title, :description, :price, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
	# def nacenka
	# 	n = if current_user.role = "admin"
	# 		...
	# end

end

app/views/application/_messages.html.slim
- flash.each do |type, content|
  div(class="callout #{type}" data-closable)
    = content
    button.close-button(tabindex="0" aria-label="Dismiss alert" type="button" data-close)
      span aria-hidden="true" &times;

app/views/application/_navigation.html.slim
.top-bar
  .top-bar-left
    .dropdown.menu data-dropdown-menu=true
      li.menu-text
        = link_to "Diabet-shop", root_path
      li.has-submenu
        a href="#" Categories
        ul.submenu.menu.vertical data-submenu=true
          <li><a href="#0">Test-links</a></li>
          <li><a href="#0">Insuine</a></li>
          <li><a href="#0">Pumps</a></li>
      li
        a href="/products" All products
      / li
      /   = link_to 'New Product', new_product_path if current_user.administrator?
      li
        - if user_signed_in?
          = link_to "Sign out", destroy_user_session_path, method: :delete
        - else
          = link_to "Sign in", new_user_session_path

  .top-bar-right
    ul.menu
      li
        = form_tag products_path, method: :get
          = text_field_tag :search, params[:search], placeholder: "Search"

app/views/comments/_comment.html.slim
.comment.callout data-id=comment.id
  .float-left.text
    = comment.text
  .float-right
    = link_to "delete", comment, method: :delete, remote: true, class: "button small"
  .clearfix
  .created_at_h
    = comment.created_at_h

app/views/comments/_form.html.slim
= form_for [product, comment], remote: true do |f|
  - if comment.errors.any?
    #error_explanation
      h2 = pluralize(comment.errors.count, "error")
        | prohibited this comment from being saved:

      ul
        - comment.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :text, "Add new comment:"
    = f.text_area :text

  .actions
    = f.submit class: "button success"

app/views/comments/create.js.erb
$(".comments").prepend("<%= j render @comment %>");

app/views/comments/destroy.js.erb
$(".comment[data-id=<%= @comment.id%>]").remove();

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

<!-- h1 editComment
	= render 'form', comment: @comment
	= link_to 'Show', @comment
	= link_to 'Back', comments_path
 -->

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.product_id %></td>
        <td><%= comment.text %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>


<!-- p #notice

h1 Comments

table
  thead
    tr
      th Product
      th Text
      th colspan="3"

  tbody
    @comments.each do |comment|
      tr
        td = comment.product_id
        td = comment.text
        td = link_to 'Show', comment
        td = link_to 'Edit', edit_comment_path(comment)
        td = link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }
      
br

= link_to 'New Comment', new_comment_path
 -->

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @comment.product_id %>
</p>

<p>
  <strong>Text:</strong>
  <%= @comment.text %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.slim
doctype html
html
  head
    title DiabetShop
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

  body
    = render "navigation"

    .container
      = render "messages"
      = yield

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.slim
.row
  .medium-12.columns
    - if params[:search]
      h3 Found products
    - else
      h3 All products
    .products
      - @products.each do |product|
        .product-short-desc
          .title = link_to product.title, product
          .description = product.truncated_description
          .price = product.price
          .amount = product.current_amount
          .actions 
            - if ProductPolicy.new(product, current_user).destroy?
              = link_to "Удалить товар", product, method: :delete


/ .row
/   .medium-6.columns
/     .products
/     h1 Products

/     - @products.each do |product|
/       .product-short-desc
/         .title = link_to product.title, product
/         .description = product.description
/         .price = product.price
/         .amount = "На складе: #{product.amount} шт."



/   .medium-6.columns
/     p
/       |Колонка справа
/     = link_to 'New Product', new_product_path if current_user.administrator?

app/views/products/new.html.slim
.row
  .medium-6.medium-centered.columns
    h3 New Product

    = render 'form', product: @product

app/views/products/show.html.slim
/ .product-full-desc
/   .title = link_to @product.title, @product
/   .description = @product.description
/   .price = @product.price
/   .amount = "На складе: #{@product.amount} шт."

/   .actions
/     => link_to 'Show', @product
/     => link_to 'Edit', edit_product_path(@product)
/     => link_to 'Destroy', @product, method: :delete, data: { confirm: 'Are you sure?' }

/ .comments
/   - @product.comments.each do |comment|
/     = render comment
/   hr
/   = render "comments/form", product: @product, comment: @product.comments.new

.row
  .medium-6.medium-centered.columns
    .product-full-desc
      .title = link_to @product.title, @product
      .description = @product.description
      .price = @product.price
      .amount = "На складе: #{@product.amount} шт."
      .action
      	- if @policy.destroy?
      		= link_to "Удалить товар", @product, method: :delete


    = render "comments/form", product: @product, comment: @comment

    .comments = render @product.comments